version: '3'

services:
  traefik:
    image: traefik
    restart: always
    command: --docker \
      --web \
      --loglevel=DEBUG
    ports:
      - 8000:80
      - 44300:443
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
         constraints: 
           - node.hostname == master
networks:
  traefik-net:
    external: true
