version: '3'

services:
  traefik:
    image: traefik
    restart: always
    command: --docker \
      --docker.swarmmode \
      --docker.watch \
      --net \
      --loglevel=DEBUG \
      --defaultentrypoints="https"
    ports:
      - 8000:80
      - 44300:443
      - 9090:8080
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
         constraints: 
           - node.hostname == master
networks:
  net:
    external: true
