# traefik.toml

# Global configuration
debug = true
logLevel = "DEBUG"

# Web configuration backend
[web]
address = ":8080"

# Entrypoints
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
     entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "bluxomous.com"
watch = true
swarmmode = true
exposedbydefault = false

# Let’s Encrypt configuration
[acme]
email = "guythomas721@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[[acme.domains]]
  main = "engauge.xyz"
  sans = [ "app.engauge.xyz" ]
[[acme.domains]]
  main = "guythomas.me"
  sans = [ "fc.guythomas.me", "flashcards.guythomas.me" ]
